################################
# Experiment Parameters        #
################################
epochs: 300
iters_per_checkpoint: 1000
seed: 228
use_all_gpu: False
fp16_opt_level: O2
ignore_layers: ['embedding.weight']
model_class_name: 'Tacotron2Embedded'
device: 'cuda:0'

################################
# Data Parameters              #
################################
load_mel_from_disk: False
data_directory: '/home/e.timofeev/data/multispeaker_new/dataset'
tokenizer_class_name: 'RussianPhonemeTokenizer'

# Audio preprocessors
audio_preprocessors:
  SilenceTrimmer:
    db_threshold: 30

################################
# Audio Parameters             #
################################
max_wav_value: 32768.0
sampling_rate: 16000
filter_length: 1024
hop_length: 200
win_length: 800
n_mel_channels: 80
mel_fmin: 0.0
mel_fmax: 8000.0

################################
# Model Parameters             #
################################
symbols_embedding_dim: 512

# Encoder parameters
encoder_kernel_size: 5
encoder_n_convolutions: 3
encoder_embedding_dim: 512
use_midlayer: False

# Decoder parameters
n_frames_per_step: 1  # currently only 1 is supported
decoder_rnn_dim: 1024
prenet_dim: 256
max_decoder_steps: 1000
gate_threshold: 0.5
p_attention_dropout: 0.1
p_decoder_dropout: 0.1

# Attention parameters
attention_rnn_dim: 1024
attention_dim: 128

# Location Layer parameters
attention_location_n_filters: 32
attention_location_kernel_size: 31

# Mel-post processing network parameters
postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 5

################################
# Optimization Hyperparameters #
################################
learning_rate: 1e-4
lr_reduce_patience: 3
lr_reduce_factor: 0.5

weight_decay: 1e-6
grad_clip_thresh: 0.5
batch_size: 60
accum_steps: 1
mask_padding: True  # set model's padded outputs to padded values
